### ISSUE TITLE
Kata 000 setting up chorus uses paramsets, but introduced in 007

### ISSUE THREAD

**Issue by risdenk** [querqy/chorus#101]
Kata 007 introduces paramsets, but they are used in 000 now? It might help to add a link to expand on why paramsets. Introduced in PR #89

**Comment by risdenk** [comment]
FYI @wrigleyDan

**Comment by epugh** [comment]
Going to look more at this one ;-)

**Comment by wrigleyDan** [comment]
The frontend (Blacklight) relies on the ParamSets being present to follow the Katas, so I included them in Kata 000. The `quickstart.sh` script introduces ParamSets, but Kata 000 did not. So if you went for the manual setup in Kata 000 you end up seeing no effect after your active searchandizing in Kata 001 (and others).

See blacklight/app/controllers/catalog_controller.rb for how the ParamSets are used by Blacklight.

**Comment by epugh** [comment]
I think this is closable, holler if not!
