### ISSUE TITLE
Kata 007 has two different topics - both starting with 007

### ISSUE THREAD

**Issue by risdenk** [querqy/chorus#102]
007 is both paramsets and security?

`katas/007_security_in_chorus.md` and `katas/007_organize_algorithms_using_paramsets.md`

I think the security kata should be moved to a later number since it doesn't look fleshed out yet.

**Comment by epugh** [comment]
Good yes.    Honestly the `katas/007_security_in_chorus.md` may just need to "disappear"...   One of the goals of Chorus is to model best practices, which would presume that we START with security from kata 000.   So every Kata, when it introduces something, should have security as part of it.    `007_security_in_chorus.md` comes from when I was messing with Keycloak, and at this piont should probably be deleted, and any info about security rolled into the other katas, probably 000.

**Comment by risdenk** [comment]
Removed in PR #104 - there isn't any content in `katas/007_security_in_chorus.md` that makes sense to move to `000` or any other kata that I could tell.

**Comment by epugh** [comment]
I think this is closeable, please holler if it isn't!
