### ISSUE TITLE
Error processing the request. CoreContainer is either not initialized or shutting down.

### ISSUE THREAD

**Issue by hahmad748** [querqy/chorus#113]
<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 404 javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.</h2>

URI: | /solr/
-- | --
404
javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.
default
javax.servlet.ServletException: javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.
javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.

<h3 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Caused by:</h3><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">javax.servlet.ServletException: javax.servlet.UnavailableException: Error processing the request. CoreContainer is either not initialized or shutting down.</pre>

### **LOGS:**

solr1            | 2022-04-04T11:19:55.968916581Z 2022-04-04 11:19:55.968 INFO  (main) [   ] o.a.s.c.ZkController Register node as live in ZooKeeper:/live_nodes/172.31.0.9:8983_solr
solr1            | 2022-04-04T11:19:56.048754867Z 2022-04-04 11:19:56.047 INFO  (zkCallback-12-thread-1) [   ] o.a.s.c.c.ZkStateReader Updated live nodes from ZooKeeper... (2) -> (3)
solr1            | 2022-04-04T11:19:56.189361493Z 2022-04-04 11:19:56.188 INFO  (main) [   ] o.a.s.p.PackageLoader /packages.json updated to version -1
solr1            | 2022-04-04T11:19:56.247212248Z 2022-04-04 11:19:56.246 INFO  (main) [   ] o.a.s.c.CoreContainer Initializing authorization plugin: solr.MultiAuthRuleBasedAuthorizationPlugin
solr1            | 2022-04-04T11:19:56.314005852Z 2022-04-04 11:19:56.313 INFO  (main) [   ] o.a.s.c.CoreContainer Initializing authentication plugin: solr.MultiAuthPlugin
solr1            | 2022-04-04T11:19:56.349467571Z 2022-04-04 11:19:56.348 ERROR (main) [   ] o.a.s.s.SolrDispatchFilter Could not start Solr. Check solr/home property and the logs
solr1            | 2022-04-04T11:19:56.421782378Z 2022-04-04 11:19:56.377 ERROR (main) [   ] o.a.s.c.SolrCore null => org.apache.solr.common.SolrException: Well-known config could not be read from url http://keycloak:9080/auth/realms/chorus/.well-known/openid-configuration
solr1            | 2022-04-04T11:19:56.421837225Z 	at org.apache.solr.security.JWTIssuerConfig$WellKnownDiscoveryConfig.parse(JWTIssuerConfig.java:402)
solr1            | 2022-04-04T11:19:56.421922679Z org.apache.solr.common.SolrException: Well-known config could not be read from url http://keycloak:9080/auth/realms/chorus/.well-known/openid-configuration
solr1            | 2022-04-04T11:19:56.422210140Z 	at org.apache.solr.security.JWTIssuerConfig$WellKnownDiscoveryConfig.parse(JWTIssuerConfig.java:402) ~[?:?]
solr1            | 2022-04-04T11:19:56.422263421Z 	at org.apache.solr.security.JWTIssuerConfig.fetchWellKnown(JWTIssuerConfig.java:184) ~[?:?]
solr1            | 2022-04-04T11:19:56.422277001Z 	at org.apache.solr.security.JWTIssuerConfig.init(JWTIssuerConfig.java:104) ~[?:?]
solr1            | 2022-04-04T11:19:56.422286342Z 	at org.apache.solr.security.JWTAuthPlugin.lambda$parseIssuers$2(JWTAuthPlugin.java:259) ~[?:?]
solr1            | 2022-04-04T11:19:56.422293296Z 	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422298976Z 	at org.apache.solr.security.JWTAuthPlugin.parseIssuers(JWTAuthPlugin.java:257) ~[?:?]
solr1            | 2022-04-04T11:19:56.422303955Z 	at org.apache.solr.security.JWTAuthPlugin.init(JWTAuthPlugin.java:174) ~[?:?]
solr1            | 2022-04-04T11:19:56.422309692Z 	at org.apache.solr.security.MultiAuthPlugin.initPluginForScheme(MultiAuthPlugin.java:147) ~[?:?]
solr1            | 2022-04-04T11:19:56.422314501Z 	at org.apache.solr.security.MultiAuthPlugin.init(MultiAuthPlugin.java:129) ~[?:?]
solr1            | 2022-04-04T11:19:56.422319708Z 	at org.apache.solr.core.CoreContainer.initializeAuthenticationPlugin(CoreContainer.java:500) ~[?:?]
solr1            | 2022-04-04T11:19:56.422324982Z 	at org.apache.solr.core.CoreContainer.reloadSecurityProperties(CoreContainer.java:987) ~[?:?]
solr1            | 2022-04-04T11:19:56.422330295Z 	at org.apache.solr.core.CoreContainer.load(CoreContainer.java:735) ~[?:?]
solr1            | 2022-04-04T11:19:56.422335976Z 	at org.apache.solr.servlet.SolrDispatchFilter.createCoreContainer(SolrDispatchFilter.java:287) ~[?:?]
solr1            | 2022-04-04T11:19:56.422341294Z 	at org.apache.solr.servlet.SolrDispatchFilter.init(SolrDispatchFilter.java:184) ~[?:?]
solr1            | 2022-04-04T11:19:56.422346522Z 	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:140) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422351804Z 	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:731) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422362559Z 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422368213Z 	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422373783Z 	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422379105Z 	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422401953Z 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422408900Z 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449) ~[jetty-webapp-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422429698Z 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414) ~[jetty-webapp-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422434818Z 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:910) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422459973Z 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422465806Z 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524) ~[jetty-webapp-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422470895Z 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422476296Z 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422481475Z 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422487274Z 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422492695Z 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422497996Z 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422503508Z 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422527623Z 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422533001Z 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422538231Z 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422543308Z 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422548668Z 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422553978Z 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422565182Z 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422570957Z 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422576186Z 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422581520Z 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422586901Z 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422592165Z 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422597666Z 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422605304Z 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:426) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422610937Z 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422616204Z 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422621304Z 	at org.eclipse.jetty.server.Server.start(Server.java:423) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422626402Z 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422631713Z 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422636955Z 	at org.eclipse.jetty.server.Server.doStart(Server.java:387) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422641856Z 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422647395Z 	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$3(XmlConfiguration.java:1907) ~[jetty-xml-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422652783Z 	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
solr1            | 2022-04-04T11:19:56.422657863Z 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1857) ~[jetty-xml-9.4.44.v20210927.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422663085Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
solr1            | 2022-04-04T11:19:56.422668042Z 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422677763Z 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422683041Z 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422688213Z 	at org.eclipse.jetty.start.Main.invokeMain(Main.java:218) ~[start.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422693607Z 	at org.eclipse.jetty.start.Main.start(Main.java:491) ~[start.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422699566Z 	at org.eclipse.jetty.start.Main.main(Main.java:77) ~[start.jar:9.4.44.v20210927]
solr1            | 2022-04-04T11:19:56.422704803Z Caused by: java.net.ConnectException: Connection refused (Connection refused)
solr1            | 2022-04-04T11:19:56.422710126Z 	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
solr1            | 2022-04-04T11:19:56.422716700Z 	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422722227Z 	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422727177Z 	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422732328Z 	at java.net.Socket.connect(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422737222Z 	at java.net.Socket.connect(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422742340Z 	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422747387Z 	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422752551Z 	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422757785Z 	at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422763239Z 	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422768165Z 	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422773164Z 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422778227Z 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422783390Z 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422788382Z 	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422793368Z 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422798631Z 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422803794Z 	at java.net.URL.openStream(Unknown Source) ~[?:?]
solr1            | 2022-04-04T11:19:56.422808817Z 	at org.apache.solr.security.JWTIssuerConfig$WellKnownDiscoveryConfig.parse(JWTIssuerConfig.java:398) ~[?:?]
solr1            | 2022-04-04T11:19:56.422814448Z 	... 63 more
solr1            | 2022-04-04T11:19:56.443173250Z 2022-04-04 11:19:56.442 INFO  (main) [   ] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@3276732{/solr,file:///opt/solr-8.11.1/server/solr-webapp/webapp/,AVAILABLE}{/opt/solr-8.11.1/server/solr-webapp/webapp}
solr1            | 2022-04-04T11:19:56.484608032Z 2022-04-04 11:19:56.483 INFO  (main) [   ] o.e.j.s.AbstractConnector Started ServerConnector@18c5069b{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:8983}
solr1            | 2022-04-04T11:19:56.488124641Z 2022-04-04 11:19:56.487 INFO  (main) [   ] o.e.j.s.Server Started @46186ms

**Comment by epugh** [comment]
Did you add "keycloak" to your /etc/hosts file?     THere *should* have been a check when you ran the quickstart.sh script to prompt you to add that....

**Comment by hahmad748** [comment]
Yes, I have added keycloak into the /etc/hosts file, and is accessible pretty well via keycloak:9080,
am facing an issue when the quickstart script goes for SOLR start.

**Comment by hahmad748** [comment]
![Screenshot from 2022-04-05 00-10-46](https://user-images.githubusercontent.com/42300494/161615107-eab131c1-20f7-4952-b7ad-e32a7806c405.png)

**Comment by hahmad748** [comment]
Now am getting this error message

**Comment by hahmad748** [comment]
> Did you add "keycloak" to your /etc/hosts file? THere _should_ have been a check when you ran the quickstart.sh script to prompt you to add that....

Can you guide me, how to overcome this issue?

**Comment by epugh** [comment]
Thanks for following up @hahmad748 !    Can you check how much memory and cpu you have allocated to Docker?   I *think* that it may be that you are running out of resources inside of the Docker environment.

Here is what mine is set to:

![image](https://user-images.githubusercontent.com/22395/163386806-19cf07bc-71c8-4b7b-8bf4-cf1d04d28467.png)

**Comment by epugh** [comment]
BTW, looking at your screens shot, I think you are getting past the Solr start step?    Can you share a log of what is emitted from quickstart.sh?   Also, that ZK connection error is a false warning, you can ignore it.

**Comment by nabeelcartlow** [comment]
> BTW, looking at your screens shot, I think you are getting past the Solr start step? Can you share a log of what is emitted from quickstart.sh? Also, that ZK connection error is a false warning, you can ignore it.

I am using Ubuntu 20.04 and when I run using quickstart.sh one of containers i.e. solr1, solr2, solr3, or keyclock exit during process. Mostly it happens at below steps:
![1](https://user-images.githubusercontent.com/103023653/163762030-0eeb3860-4c37-42eb-9044-b75084a10887.png)
![3](https://user-images.githubusercontent.com/103023653/163763507-213e7a6c-e165-4103-ad0d-128afaa43301.png)
![5](https://user-images.githubusercontent.com/103023653/163766116-673e082d-4357-4227-9b35-93f82b3c34ef.png)

but it's not limited to above, it happens randomly. For instance when I tried `docker-compose up` (--build was used first time and then omitted, tried with it as well) the error was different i.e. solr started but keyclock failed and error "CoreContainer is either not initialized or shutting down."  starts being display in console.

I checked and there were some solutions to increase memory or enable swap for docker but that didn't help me out here as well. The error persists and it's totally weird that sometimes it works but sometimes it doesn't and I can't see any reason behind it.

`docker info` logs below:
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 22
  Running: 16
  Paused: 0
  Stopped: 6
 Images: 40
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-39-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 14.46GiB
 Name: ########
 ID: #############################
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by epugh** [comment]
Looking at the error message, "no registered leader....", and then this stackoverflow, https://stackoverflow.com/questions/47868737/solr-cloud-no-registered-leader-was-found-after-waiting-for-4000ms, I think your docker environment doesn't have enough resources.   Looks like from the log you are running 16 containers?   Do a `docker system prune`, and then try....   Also, maybe try spinning up a cloud EC2 instance or soemthing and trying it there!

**Comment by epugh** [comment]
I'm going to close this for now....   Please holler if you run into other issues....
