### ISSUE TITLE
Update sample icecat data file to have fully specified date time  format for date_released field

### ISSUE THREAD

**Issue by epugh** [querqy/chorus#13]
Hey @renekrie can you make the date_released field be in the proper full format that Solr wants by default?   

I don't see a good reason to have to demonstrate converting date time stamps since we control the source file!

date_released'='2009-12-10' should be '2009-12-10T00:00:00Z`

Thanks!

**Comment by epugh** [comment]
For reference, I get rid of the field when creating a .jsonl format file via the magic of `jq`:

```
jq -c '.[] | del(.date_released)' icecat-products-150k-20200607.json > icecat-products-150k-20200607.jsonl
```

**Comment by renekrie** [comment]
Fixed. The new dataset is available at:  https://querqy.org/datasets/icecat/icecat-products-150k-20200809.tar.gz (also includes a new `price` field for 20k products and `ean` is multiValued now)

**Comment by renekrie** [comment]
@epugh Let's change the README to the new dataset once prices become available in the UI.

**Comment by epugh** [comment]
See https://github.com/querqy/chorus/pull/14
