### ISSUE TITLE
Move default data filters into Solr request handler from UI

### ISSUE THREAD

**Issue by epugh** [querqy/chorus#15]
I'm opening up this issue to ask a question: Should the default data quality related filters live in the Solr Request Handler?   

We've added two filters to the Blacklight front end, one to ensure we only show products with prices, the other for images:

```
      fq: '-img_500x500:""',
      fq: 'price:*'
```

I then was poking around with the data, and was getting conflicting results between Quepid and Blacklight, and my python script and Blacklight, which I finally realized was because I wasn't keeping those parameters in Solr!   

Maybe on a larger point, should all data filters like this always live in the search layer?   Since we don't have a "Search API" that is seperate, then that makes the Solr /select basically our API.

**Comment by renekrie** [comment]
Hm, shouldn't we fix this in the dataset? (that would be best practice ;-) ) 

We could provide two datasets - one 'clean' dataset, only containing documents that have both, price and image, and a second dataset that contains all documents, for those that want to play with a slightly larger dataset. Quepid would rely on the clean dataset.

**Comment by epugh** [comment]
That probably makes a lot of sense...   We'll end up having a number of different datasets over time as this progresses.   

So...  I think you are currently the keeper of data?   I wondered about having a `notebooks` or `chorus-notebooks` github project with scripts etc...   Or maybe, like what we do on the `solr-tmdb` project, is have a nested Housekeeping directory: https://github.com/o19s/solr-tmdb/tree/master/housekeeping where scripts etc all live, but aren't necessarily something a direct user would need to run!

**Comment by epugh** [comment]
Filters for image and price existence moved into the Solr request handelrs.
