### ISSUE TITLE
Document the Data Encoder process

### ISSUE THREAD

**Issue by atarora** [querqy/chorus#153]
The dataencoder process currently is part of the chorus repo. It misses the README and the steps required to run and (if required) customise based on the chosen transformer.

**Comment by mkr** [comment]
Thanks, please document the steps I need to run this locally. Also, we need some kind of [dependency](https://venthur.de/2022-12-18-python-packaging.html) file, i.e. a `requirements.txt` for pip or a `pyproject.toml` for poetry.

**Comment by atarora** [comment]
Addressed as part of : https://github.com/querqy/chorus/pull/152/files.
I think the issue can be closed now.
