### ISSUE TITLE
Upgrade Party!

### ISSUE THREAD

**Issue by epugh** [querqy/chorus#16]
* Upgrade to latest Querqy when it is released (probably 4.10)
* Bump Solr
* Bump to latest SMUI
* Run through the scripts to verify things still work.

**Comment by epugh** [comment]
@pbartusch and I are going to chat about how to get the Rules.txt into ZK, instead of doing the filesystem writing out of file, which would be more SolrCloud "native" approach.   This is a direct hack, but would work.  

Longer term, we'll have a proper API in Querqy in Solr that will get the rules.txt into ZK but @renekrie is still working on this.

**Comment by renekrie** [comment]
`4.10.lucene810.0` it is for querqy-solr (just released)

**Comment by epugh** [comment]
@pbartusch here is the issue to track bumping SMUI and Querqy dependencies.

**Comment by pbartusch** [comment]
hi @renekrie , just talked to @epugh ...

we should consider updating the chorus setup to use spellings (ReplaceRewriter) and maybe a separate decompound rewriter.

for now, I will deactivate both for SMUI in chorus, but maybe we can deal with this extension in a follow-up CR?
