### ISSUE TITLE
*Vector Demo Blocker* - Required Product Vector dataset + Product Finetuned vectors dataset path updates

### ISSUE THREAD

**Issue by atarora** [querqy/chorus#162]
The path updates as required in the index-vectors.sh :    

Product vectors path updates to : s3://o19s-public-datasets/chorus/product-vectors-2023-03-23/ <file names remains>

Product finetuned vectors path updates to : s3://o19s-public-datasets/chorus/product-finetuned-vectors-2023-06/ <file names remains>

**Note:** This is a blocker for the vector demo

**Comment by atarora** [comment]
The designated changes have rather been made on the AWS side. 
Needs to be retested with the complete flow.
Can you test @mkr  ?

**Comment by atarora** [comment]
@mkr confirmed this works again, closing it! Thanks!!

**Comment by epugh** [comment]
nice!
