### ISSUE TITLE
Use v2 Configset API to update rules.txt

### ISSUE THREAD

**Issue by epugh** [querqy/chorus#22]
Once Solr 8.7 is cut, use the new SOLR-14907 v2 Configset API to update rules.txt in zookeeper, which lets us remove our `jackhanna.jar` file that directly inserts rules.txt into ZooKeeper.

We may be able to avoid doing a manual reload on the collection as well, not sure on that ;-)

Thanks @HoustonPutman for adding this to Solr!

**Comment by HoustonPutman** [comment]
Glad this helps! v1 support is there now, but v2 support is not yet merged. https://github.com/apache/lucene-solr/pull/1996

Hopefully v2 makes it into 8.7, if not then 8.8...

**Comment by epugh** [comment]
Solr 8.7 is released, and specifically we are interested in SOLR-14907.   So we can now do this!

**Comment by epugh** [comment]
Look at https://lucene.apache.org/solr/guide/8_7/configsets-api.html#configsets-upload for more details.

**Comment by epugh** [comment]
THis may be OBE by other efforts...?   Not sure yet.

**Comment by epugh** [comment]
Okay, I think this is OBE.

**Comment by epugh** [comment]
Querqy5 dealt with this in a different way!
