### ISSUE TITLE
High Solr response time

### ISSUE THREAD

**Issue by renekrie** [querqy/chorus#31]
Response times are high (in the 30-50 ms range) at Solr level regardless of which query parser we use (querqy or edismax). ms should be in the slow single digits, even on a not-so-fast machine.

Query:  http://localhost:8983/solr/ecommerce/select?q=laptop&defType=edismax

Guess: JVM heap (500m) looks a bit small to me.

**Comment by epugh** [comment]
![Screenshot at Feb 22 14-04-07](https://user-images.githubusercontent.com/22395/108756778-fda34c80-7516-11eb-9bc3-7a4c136e142c.png)
![Screenshot at Feb 22 14-04-43](https://user-images.githubusercontent.com/22395/108756786-ff6d1000-7516-11eb-8d3b-2aea732e9d17.png)

Dusted off an old tool, SolrMeter, to get these screenshots.  The query time is averaging 52 ms ;-).    

https://github.com/adelean/solrmeter is the version I used.

**Comment by epugh** [comment]
I've mucked around with trying to increase Docker allocated resources, and moving SOLR_HEAP to 800m and 1g, and the best I can do is 30 ms....     

I think this is also part of just running multiple servers all in a Docker environment, and they are competing for resources.   

![Screenshot at Feb 22 15-26-59](https://user-images.githubusercontent.com/22395/108766023-9a1f1c00-7522-11eb-97dc-b094571413f1.png)
