### ISSUE TITLE
Demo "Chorus Electronics" link not working

### ISSUE THREAD

**Issue by KShivendu** [querqy/chorus#55]
Hi, the demo "Chorus Electronics" link (http://chorus.dev.o19s.com:4000/) isn't working. Rest of the applications are runnning and are accessible through their respective ports. Please take a look. 

Cheers !

**Comment by epugh** [comment]
Hi, I put some new text in the Readme that this is often not running...  

I am going to take another stab at updating the demo app to see if I can get it to run more reliably.  Not sure why it doesn't, I have other Rails apps that run great in Docker Compose based setups for days and days!!!!

**Comment by epugh** [comment]
@KShivendu I've done a massive rewrite/update of the Demo app....    It's still up and running 24 hours after I deployed it, and it used to get slow after 24 hours and not respond at all after 36 hours.    So fingers crossed that this is now Fixed Fixed!

I'm going to close this ticket.
