### ISSUE TITLE
README.md updates

### ISSUE THREAD

**Issue by bab178** [querqy/chorus#7]
Change this line from:
> curl 'http://localhost:8983/solr/ecommerce/update?processor=formatDateUpdateProcessor&commit=true' --data-binary @icecat-products-150k-20200607.tar.gz -H 'Content-type:application/json'

to 

> curl 'http://localhost:8983/solr/ecommerce/update?processor=formatDateUpdateProcessor&commit=true' --data-binary @icecat-products-150k-20200607.json -H 'Content-type:application/json'

Change meaninfully to meaningfully in the That all folks! paragraph

**Comment by epugh** [comment]
Hey @bab178 want to throw this small change in as a PR?   Get you some "I contributed" points ;-)   Thanks for this!
