### ISSUE TITLE
Documentation 'First Kata: Lets Optimize a Query' refers to nDCG@5 that is not available

### ISSUE THREAD

**Issue by Paul-Blanchaert** [querqy/chorus#71]
Documentation 'First Kata: Lets Optimize a Query' instructs to set scorer to nDCG@5, but that option is not available in the scorers drop down.
Further in the document nDCG@4 (and the available option nDCG@10) is also referred to.
The available options are:
- nDCG@10 (Communal)
- DCG@10 (Communal)
- CG@10 (Communal)
- P@10 (Communal)
- AP@10 (Communal)

**Comment by epugh** [comment]
Thanks!  fixes applied!
