### ISSUE TITLE
Kata 6: curl command uses qt instead of defType

### ISSUE THREAD

**Issue by Paul-Blanchaert** [querqy/chorus#74]
The 2 curl commands in kata 6 (https://github.com/querqy/chorus/blob/master/katas/006_adding_custom_query_rules.md#sixth-kata-lets-understand-how-to-consume-some-common-query-patterns-with-regex) that illustrate the results from querqy use the parameter qt (qt=querqy) instead of defType (defType=querqy). This results in error message returned:
```
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"invalid query parser 'qt' for query '16:9 K58357WW'",
    "code":400}}
```

**Comment by epugh** [comment]
Good find, and this was because we used to have seperate request handlers that you accessed through the `qt` parameter, and then we just started using it as different query parsers via `defType`...    This was originally forced by an older Blacklight version we had..

**Comment by epugh** [comment]
thanks @Paul-Blanchaert
