### ISSUE TITLE
Chorus redirects users to http://keycloack:9080 but deployed version needs to be http://chorus.dev.o19s.com:9080

### ISSUE THREAD

**Issue by epugh** [querqy/chorus#87]
Ugh, the assumption that http://keycloak:9080 will work both inside the Docker Environment and Externally to the end user works fine in dev, but breaks in the hosted version!   This impacts Solr and Quepid authing against Keycloak.

**Comment by risdenk** [comment]
Relates to #91

**Comment by risdenk** [comment]
PR #99 has an example of all the changes to deploy on custom host. Should be possible to make it better, but put the PR up for posterity.

**Comment by epugh** [comment]
This has been fixed in #111.
